name: Daily EVE Fuel Check

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 09:00 UTC daily
  workflow_dispatch:     # Also allow manual runs from GitHub UI

jobs:
  run-fuelbot:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
      EVE_REFRESH_TOKEN: ${{ secrets.EVE_REFRESH_TOKEN }}  # Make sure this is your raw refresh token

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Create refresh token file
        run: |
          python -c "import json; json.dump({'refresh_token': '${{ secrets.EVE_REFRESH_TOKEN }}'}, open('refresh_token.txt', 'w'))"

      - name: Run fuel alert bot
        run: python fuel_alert_bot.py
