name: Daily EVE Fuel Check

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run-fuelbot:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Create token file
        run: |
          python -c "import json; json.dump({'refresh_token': '${{ secrets.EVE_TOKENS_JSON }}'}, open('eve_tokens.json', 'w'))"

      - name: Run fuel alert bot
        run: python fuel_alert_bot.py
